# Generated by Django 5.2.6 on 2026-08-24 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گروه')),
                ('code', models.CharField(max_length=10, verbose_name='کد گروه')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to=settings.AUTH_USER_MODEL, verbose_name='مدیر گروه')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='account_module.university', verbose_name='دانشگاه')),
            ],
            options={
                'verbose_name': 'گروه آموزشی',
                'verbose_name_plural': 'گروه\u200cهای آموزشی',
                'indexes': [models.Index(fields=['university'], name='panel_modul_univers_1b666e_idx')],
                'unique_together': {('code', 'university')},
            },
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'ورود'), ('logout', 'خروج'), ('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('schedule', 'زمان\u200cبندی')], max_length=20)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_logs', to='account_module.university', verbose_name='دانشگاه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'لاگ سیستم',
                'verbose_name_plural': 'لاگ\u200cهای سیستم',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['university'], name='panel_modul_univers_93ca6a_idx'), models.Index(fields=['user'], name='panel_modul_user_id_45d8cd_idx'), models.Index(fields=['action'], name='panel_modul_action_079975_idx')],
            },
        ),
    ]
