# Generated by Django 5.2.6 on 2026-08-24 00:27

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('supervisor', 'سوپروایزر کل'), ('admin', 'مدیر دانشگاه'), ('education_officer', 'مسئول آموزش'), ('teacher', 'استاد')], default='teacher', max_length=20, verbose_name='نقش')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن')),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن')], max_length=10, null=True, verbose_name='جنسیت')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d/', verbose_name='تصویر پروفایل')),
                ('department', models.CharField(blank=True, max_length=100, null=True, verbose_name='دانشکده')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('email_verified', models.BooleanField(default=False, verbose_name='ایمیل تایید شده')),
                ('phone_verified', models.BooleanField(default=False, verbose_name='تلفن تایید شده')),
                ('failed_login_attempts', models.IntegerField(default=0, verbose_name='تعداد تلاش ناموفق')),
                ('lockout_until', models.DateTimeField(blank=True, null=True, verbose_name='قفل شده تا')),
                ('last_password_change', models.DateTimeField(auto_now_add=True, verbose_name='آخرین تغییر رمز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['-date_joined'],
                'permissions': [('can_manage_universities', 'می\u200cتواند همه دانشگاه\u200cها را مدیریت کند (سوپروایزر)'), ('can_manage_university', 'می\u200cتواند دانشگاه را مدیریت کند'), ('can_manage_courses', 'می\u200cتواند دروس را مدیریت کند'), ('can_manage_teachers', 'می\u200cتواند اساتید را مدیریت کند'), ('can_view_schedule', 'می\u200cتواند برنامه را مشاهده کند')],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام دانشگاه/دانشکده')),
                ('subdomain', models.SlugField(help_text='فقط حروف کوچک انگلیسی، اعداد و خط تیره (مثلاً: eng برای eng.example.com)', max_length=63, unique=True, verbose_name='زیردامنه')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='university_logos/', verbose_name='لوگو')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل تماس')),
                ('contact_phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن تماس')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('valid_from', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ شروع اعتبار')),
                ('valid_until', models.DateTimeField(blank=True, help_text='اگر خالی باشد، اعتبار نامحدود است', null=True, verbose_name='تاریخ پایان اعتبار')),
                ('max_users', models.IntegerField(default=50, verbose_name='حداکثر تعداد کاربران')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_universities', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط (سوپروایزر)')),
            ],
            options={
                'verbose_name': 'دانشگاه',
                'verbose_name_plural': 'دانشگاه\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='university',
            field=models.ForeignKey(blank=True, help_text='برای سوپروایزر خالی است (دسترسی سراسری دارد)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='account_module.university', verbose_name='دانشگاه'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='بیوگرافی')),
                ('address', models.TextField(blank=True, max_length=300, verbose_name='آدرس')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('educational_background', models.TextField(blank=True, max_length=1000, verbose_name='سوابق تحصیلی')),
                ('expertise', models.TextField(blank=True, max_length=500, verbose_name='تخصص\u200cها')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, verbose_name='تماس اضطراری')),
                ('emergency_phone', models.CharField(blank=True, max_length=15, verbose_name='تلفن اضطراری')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='اعلان\u200cهای ایمیلی')),
                ('sms_notifications', models.BooleanField(default=True, verbose_name='اعلان\u200cهای پیامکی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل کاربر',
                'verbose_name_plural': 'پروفایل\u200cهای کاربران',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['subdomain'], name='account_mod_subdoma_4ed408_idx'),
        ),
        migrations.AddIndex(
            model_name='university',
            index=models.Index(fields=['is_active'], name='account_mod_is_acti_54b992_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='account_mod_email_bb4cd2_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['national_code'], name='account_mod_nationa_1525eb_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role'], name='account_mod_role_40d77c_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active'], name='account_mod_is_acti_12b3fd_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='account_mod_user_id_2e69d7_idx'),
        ),
    ]
