# Generated by Django 5.2.6 on 2026-08-24 00:27

import django.db.models.deletion
import scheduling_module.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='کد مکان')),
                ('name', models.CharField(max_length=255, verbose_name='نام مکان')),
                ('capacity', models.IntegerField(verbose_name='ظرفیت')),
                ('place_type', models.CharField(choices=[('کلاس تئوری', 'کلاس تئوری'), ('آزمایشگاه', 'آزمایشگاه'), ('کارگاه', 'کارگاه')], max_length=20, verbose_name='نوع مکان')),
                ('gender', models.IntegerField(choices=[(0, 'مختلط'), (1, 'مرد'), (2, 'زن')], default=0, verbose_name='جنسیت')),
                ('facilities', models.JSONField(default=list, verbose_name='امکانات')),
                ('available', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مکان',
                'verbose_name_plural': 'مکان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='SchedulingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام زمان\u200cبندی')),
                ('config_file', models.FileField(blank=True, null=True, upload_to='scheduling_configs/', validators=[scheduling_module.models.validate_yaml_file], verbose_name='فایل پیکربندی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('processing', 'در حال پردازش'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='نتایج')),
                ('algorithm_params', models.JSONField(default=dict, verbose_name='پارامترهای الگوریتم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='زمان اجرا (ثانیه)')),
                ('is_public', models.BooleanField(default=False, verbose_name='عمومی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_tasks', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'وظیفه زمان\u200cبندی',
                'verbose_name_plural': 'وظایف زمان\u200cبندی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_data', models.JSONField(verbose_name='داده\u200cهای زمان\u200cبندی')),
                ('total_cost', models.FloatField(verbose_name='هزینه کل')),
                ('teacher_conflicts', models.IntegerField(default=0, verbose_name='تداخل اساتید')),
                ('place_conflicts', models.IntegerField(default=0, verbose_name='تداخل مکان\u200cها')),
                ('capacity_issues', models.IntegerField(default=0, verbose_name='مشکلات ظرفیت')),
                ('gender_mismatches', models.IntegerField(default=0, verbose_name='عدم تطابق جنسیت')),
                ('total_courses', models.IntegerField(default=0, verbose_name='تعداد کل دروس')),
                ('approval_status', models.CharField(choices=[('pending_review', 'در انتظار بررسی'), ('approved', 'تأیید شده (نهایی)'), ('rejected', 'رد شده (نیاز به بازنگری)')], default='pending_review', max_length=20, verbose_name='وضعیت تأیید')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تأیید')),
                ('rejection_note', models.TextField(blank=True, verbose_name='دلیل رد / یادداشت بازنگری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_schedule_results', to=settings.AUTH_USER_MODEL, verbose_name='تأیید شده توسط')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_result', to='scheduling_module.schedulingtask', verbose_name='وظیفه')),
            ],
            options={
                'verbose_name': 'نتیجه زمان\u200cبندی',
                'verbose_name_plural': 'نتایج زمان\u200cبندی',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='کد استاد')),
                ('full_name', models.CharField(max_length=255, verbose_name='نام کامل')),
                ('gender', models.IntegerField(choices=[(1, 'مرد'), (2, 'زن')], verbose_name='جنسیت')),
                ('degree', models.IntegerField(choices=[(1, 'کارشناسی'), (2, 'کارشناسی ارشد'), (3, 'دکتری')], verbose_name='مدرک')),
                ('employment_type', models.IntegerField(choices=[(1, 'تمام وقت'), (2, 'نیمه وقت'), (3, 'حقالتدریس')], verbose_name='نوع استخدام')),
                ('position', models.IntegerField(verbose_name='پست')),
                ('max_units', models.IntegerField(verbose_name='حداکثر واحد')),
                ('min_units', models.IntegerField(verbose_name='حداقل واحد')),
                ('unavailable_times', models.JSONField(default=list, verbose_name='زمان\u200cهای غیرقابل دسترس')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب کاربری')),
            ],
            options={
                'verbose_name': 'استاد',
                'verbose_name_plural': 'اساتید',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='کد درس')),
                ('name', models.CharField(max_length=255, verbose_name='نام درس')),
                ('course_type', models.CharField(choices=[('تئوری', 'تئوری'), ('عملی', 'عملی'), ('تئوری_عملی', 'تئوری_عملی')], max_length=20, verbose_name='نوع درس')),
                ('unit_type', models.CharField(choices=[('پایه', 'پایه'), ('تخصصی', 'تخصصی'), ('عمومی', 'عمومی')], max_length=20, verbose_name='نوع واحد')),
                ('units', models.IntegerField(verbose_name='تعداد واحد')),
                ('priority', models.IntegerField(default=1, verbose_name='اولویت')),
                ('gender', models.IntegerField(default=0, verbose_name='جنسیت')),
                ('required_place_type', models.CharField(max_length=50, verbose_name='نوع مکان مورد نیاز')),
                ('prerequisites', models.JSONField(default=list, verbose_name='پیش\u200cنیازها')),
                ('corequisites', models.JSONField(default=list, verbose_name='هم\u200cنیازها')),
                ('expected_students', models.IntegerField(verbose_name='تعداد دانشجوی مورد انتظار')),
                ('required_place', models.CharField(blank=True, max_length=20, null=True, verbose_name='مکان الزامی')),
                ('fixed', models.BooleanField(default=False, verbose_name='ثابت')),
                ('teachers', models.ManyToManyField(related_name='courses', to='scheduling_module.teacher', verbose_name='اساتید')),
            ],
            options={
                'verbose_name': 'درس',
                'verbose_name_plural': 'دروس',
            },
        ),
        migrations.CreateModel(
            name='UniversityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام پیکربندی')),
                ('semester', models.CharField(max_length=100, verbose_name='نیمسال تحصیلی')),
                ('days_of_week', models.JSONField(default=list, verbose_name='روزهای هفته')),
                ('time_slots', models.JSONField(default=list, verbose_name='بازه\u200cهای زمانی')),
                ('max_units_per_student', models.IntegerField(default=20, verbose_name='حداکثر واحد هر دانشجو')),
                ('max_classes_per_day', models.IntegerField(default=3, verbose_name='حداکثر کلاس در روز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='account_module.university', verbose_name='دانشگاه (مستأجر)')),
            ],
            options={
                'verbose_name': 'پیکربندی نیمسال',
                'verbose_name_plural': 'پیکربندی\u200cهای نیمسال',
            },
        ),
        migrations.AddField(
            model_name='teacher',
            name='university_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='scheduling_module.universityconfig'),
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام گروه')),
                ('size', models.IntegerField(default=30, verbose_name='ظرفیت گروه')),
                ('required_courses', models.JSONField(default=list, verbose_name='دروس الزامی')),
                ('optional_courses', models.JSONField(default=list, verbose_name='دروس اختیاری')),
                ('university_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_groups', to='scheduling_module.universityconfig', verbose_name='دانشگاه')),
            ],
            options={
                'verbose_name': 'گروه دانشجویی',
                'verbose_name_plural': 'گروه\u200cهای دانشجویی',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='schedulingtask',
            name='university_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduling_tasks', to='scheduling_module.universityconfig', verbose_name='دانشگاه'),
        ),
        migrations.CreateModel(
            name='ScheduleConstraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constraint_type', models.CharField(choices=[('teacher_unavailable', 'عدم دسترسی استاد'), ('concurrent_courses', 'دروس همزمان'), ('same_teacher_courses', 'دروس یک استاد'), ('place_unavailable', 'عدم دسترسی مکان'), ('time_preference', 'ترجیح زمانی')], max_length=50, verbose_name='نوع محدودیت')),
                ('parameters', models.JSONField(verbose_name='پارامترها')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('university_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='constraints', to='scheduling_module.universityconfig')),
            ],
            options={
                'verbose_name': 'محدودیت زمان\u200cبندی',
                'verbose_name_plural': 'محدودیت\u200cهای زمان\u200cبندی',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'شنبه'), (1, 'یکشنبه'), (2, 'دوشنبه'), (3, 'سه\u200cشنبه'), (4, 'چهارشنبه'), (5, 'پنجشنبه')], verbose_name='روز هفته')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('time_slot', models.CharField(max_length=50, verbose_name='بازه زمانی')),
                ('semester', models.CharField(max_length=100, verbose_name='نیمسال')),
                ('academic_year', models.CharField(max_length=20, verbose_name='سال تحصیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduling_module.place', verbose_name='کلاس')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduling_module.course', verbose_name='درس')),
                ('schedule_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_entries', to='scheduling_module.scheduleresult', verbose_name='نتیجه زمان\u200cبندی')),
                ('student_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='scheduling_module.studentgroup', verbose_name='گروه دانشجویی')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduling_module.teacher', verbose_name='استاد')),
                ('university_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduling_module.universityconfig', verbose_name='دانشگاه')),
            ],
            options={
                'verbose_name': 'برنامه زمان\u200cبندی',
                'verbose_name_plural': 'برنامه\u200cهای زمان\u200cبندی',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='place',
            name='university_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='scheduling_module.universityconfig'),
        ),
        migrations.AddField(
            model_name='course',
            name='university_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='scheduling_module.universityconfig'),
        ),
        migrations.AddIndex(
            model_name='scheduleresult',
            index=models.Index(fields=['task'], name='scheduling__task_id_b1d378_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleresult',
            index=models.Index(fields=['approval_status'], name='scheduling__approva_815ece_idx'),
        ),
        migrations.AddIndex(
            model_name='universityconfig',
            index=models.Index(fields=['created_by'], name='scheduling__created_a1bc0e_idx'),
        ),
        migrations.AddIndex(
            model_name='universityconfig',
            index=models.Index(fields=['name'], name='scheduling__name_db45b5_idx'),
        ),
        migrations.AddIndex(
            model_name='universityconfig',
            index=models.Index(fields=['university'], name='scheduling__univers_bda7ff_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['university_config'], name='scheduling__univers_31197c_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['user'], name='scheduling__user_id_e9ff35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('code', 'university_config')},
        ),
        migrations.AddIndex(
            model_name='studentgroup',
            index=models.Index(fields=['university_config'], name='scheduling__univers_e7e631_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulingtask',
            index=models.Index(fields=['created_by'], name='scheduling__created_aa6ba9_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulingtask',
            index=models.Index(fields=['status'], name='scheduling__status_15c9d9_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulingtask',
            index=models.Index(fields=['university_config'], name='scheduling__univers_e9ad0a_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleconstraint',
            index=models.Index(fields=['university_config'], name='scheduling__univers_18a81a_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['university_config'], name='scheduling__univers_823b8e_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['teacher'], name='scheduling__teacher_1f68dc_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['day_of_week', 'start_time'], name='scheduling__day_of__40eebb_idx'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['semester'], name='scheduling__semeste_cb9826_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['university_config'], name='scheduling__univers_3d0a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['available'], name='scheduling__availab_4f8c11_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='place',
            unique_together={('code', 'university_config')},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['university_config'], name='scheduling__univers_8747da_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['priority'], name='scheduling__priorit_457242_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('code', 'university_config')},
        ),
    ]
