# Generated by Django 5.2.6 on 2026-08-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_type',
            field=models.CharField(choices=[('کلاس تئوری', 'کلاس تئوری'), ('آزمایشگاه', 'آزمایشگاه'), ('کارگاه', 'کارگاه'), ('سالن ورزشی', 'سالن ورزشی'), ('استخر', 'استخر'), ('زمین چمن', 'زمین چمن'), ('سالن آمفی\u200cتئاتر', 'سالن آمفی\u200cتئاتر'), ('سالن اجتماعات', 'سالن اجتماعات'), ('کتابخانه', 'کتابخانه'), ('سایر', 'سایر')], max_length=50, verbose_name='نوع مکان'),
        ),
    ]
