# Generated by Django 5.2.6 on 2026-08-29 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_module', '0002_alter_place_place_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgroup',
            options={'ordering': ['-entry_year', 'name'], 'verbose_name': 'گروه دانشجویی', 'verbose_name_plural': 'گروه\u200cهای دانشجویی'},
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='degree_level',
            field=models.CharField(choices=[('associate', 'کاردانی'), ('bachelor', 'کارشناسی'), ('master', 'کارشناسی ارشد'), ('phd', 'دکتری')], default='bachelor', max_length=20, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='entry_year',
            field=models.IntegerField(blank=True, help_text='مثلاً ۱۴۰۳ برای دانشجویان ورودی ۱۴۰۳', null=True, verbose_name='سال ورود'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=255, verbose_name='رشته تحصیلی'),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='gender',
            field=models.IntegerField(choices=[(0, 'مختلط'), (1, 'مرد'), (2, 'زن')], default=0, help_text='برای تطبیق با جنسیت مکان و درس در الگوریتم زمان\u200cبندی', verbose_name='جنسیت گروه'),
        ),
    ]
