# Generated by Django 5.2.6 on 2026-09-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling_module", "0004_universityconfig_benchmark_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleconstraint",
            name="constraint_type",
            field=models.CharField(
                choices=[
                    ("teacher_unavailable", "عدم دسترسی استاد"),
                    ("concurrent_courses", "دروس همزمان"),
                    ("same_teacher_courses", "دروس یک استاد"),
                    ("place_unavailable", "عدم دسترسی مکان"),
                    ("time_preference", "ترجیح زمانی"),
                    (
                        "teacher_weekly_load",
                        "حداقل و حداکثر واحد هفتگی استاد (قید سخت)",
                    ),
                ],
                max_length=50,
                verbose_name="نوع محدودیت",
            ),
        ),
    ]
